### ISSUE TITLE
Invalid BSML

### ISSUE THREAD

**Issue by Henry9871** [Auros/Actions#3]
Beat Saber game version: 1.18.3
Mods installed: Actions, BSML, Chat Core, Sira Util
Vr headset: Rift S

Whenever I go into the Actions mod menu, I always get a message In big letters saying "Invalid BSML". Right under the Actions text there is a message that says "Index was out of range. Must be non-negative and less than the size of the collection. Parameter name index". But the strange thing is that the menu on the right where you make the presets work perfectly fine, its just the menu in the middle where I can not select anything. I have tried a older version of Actions but that just made my game crash completely. I also uninstalled the game and installed the core mods that Actions need to run and I still get the same message.

![Actions](https://user-images.githubusercontent.com/76413862/147374263-5e979bd2-d6d0-4f0d-86b2-cfab08c51aa7.png)

**Comment by Auros** [comment]
I will need a log file from the `Beat Saber/Logs` folder. Preferably launch the game, produce this error, close the game, and send me `_latest.log`

**Comment by Henry9871** [comment]
Here you go. I really hope I am not taking any of your time during Christmas eve/day. I also appreciate you helping me with this.

[_latest.log](https://github.com/Auros/Actions/files/7775551/_latest.log)

**Comment by Auros** [comment]
Ah, I think I see the issue. In the ChatCore window, do you have any channels in the channel list? There needs to be at least one (an oversight on my part). Soon I'll release an update to remedy this but for now make sure there's at least 1 channel in the ChatCore window.

Let me know if this is the issue and if it was resolved.

**Comment by Henry9871** [comment]
I'm sorry to ask, But what do you mean by ChatCore Window? Do you mean something in the ChatCore.dll or in the ChatCore.manifest? Also there is no menu for ChatCore in Beat Saber if that's what you were referencing.

**Comment by Auros** [comment]
You must have disabled it. With the game open, navigate to localhost:8338

**Comment by Henry9871** [comment]
Adding my twitch channel name to ChatCore channel list fixed the issue. Thanks for the help and I hope I did not take up any of your time. Marry Christmas!
